import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from './Components/Nav'
import HomeContent from './Components/HomeContent'
import Particles from 'react-particles-js';
import particlesConfig from './Components/particlesConfig';

export default function Home() {
  return (
    <div style={{ position: 'relative', overflow: "hidden" }}>
      <Head>
        <title>bunleaps - home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blossom.ico" />
      </Head>
      
      <div style={{ position: 'absolute'}}>
          <Particles height="100vh" width="100vw" params={particlesConfig} />
      </div>  

      <main className={styles.Main}>
        <Nav />
        <HomeContent />
      </main>


    </div>
  )
}
