import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from './Components/Nav'
import HomeContent from './Components/HomeContent'

// Need Monospace Font

export default function Home() {
  return (
    <div>
      <Head>
        <title>bunleaps - home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blossom.ico" />
      </Head>

      <main className={styles.Main}>
        <Nav />
        <HomeContent />
      </main>
    </div>
  )
}
